server:
  port: 5556

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/avito?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: logrys7
    initialization-mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: false
        jdbc:
          timezone: UTC

google:
  client:
    clientId: 344846477697-c2rmg5mke2phj7tah05huer1shlgdluf.apps.googleusercontent.com
    clientSecret: KuasA3K9Gpzq53U7rnovS_HQ
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope: openid,email,profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true

vk:
  client:
    clientId: 7517722
    clientSecret: gsG85MUAQiOdmSVdBogN
    accessTokenUri: https://api.vk.com/oauth/token
    userAuthorizationUri: https://oauth.vk.com/authorize?v=5.8
    scope: id,first_name,last_name,photo_50, offline
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.vk.com/method/users.get
    preferTokenInfo: true